### ISSUE TITLE
Cursor warps excessively when using eshell

### ISSUE THREAD

**Issue by duckwork** [ieure/exwm-mff#6]
I use EXWM, and I've just had a firefox window next to an eshell buffer in a split. As I was running a command, I learned that apparently eshell focuses itself with every write to the buffer because I couldn't hardly move my pointer from the center of the Firefox window.

Apparently, eshell would grab focus for a very smal amount of time, then return the focus -- which warped the pointer back to the center of the firefox window. I'm not sure if this happens with any other buffertypes or windows in Emacs.

**Comment by ieure** [comment]
I can't reproduce with c3a132164ea5fdcaa9df49d8a115eab0481ee342.  Can you try that version, or provide steps to reproduce?

The last released version uses `buffer-list-update-hook` to detect changes in window focus; I rewrote it to detect focus changes more reliably, and your symptom sounds a lot like the sorts of issues I was running into on the old version.

New release will get cut soon, I just wanted to run things for a week or so to make sure there weren't issues needing fixed with the new code.

**Comment by duckwork** [comment]
I upgraded exwm-mff and it looks like the issue is fixed. Thanks! (Sorry for the spurious issue ... I'll make sure to update before commenting next time :) )
